### ISSUE TITLE
Import failure with empty sections part

### ISSUE THREAD

**Issue by thge** [juanii/OnePIF#2]
My exported pif file form 1Password for Windows 4.6.2.626 contained one entry with an empty sections entry. This leads to an error in the import function `Object reference not set to an instance of object` and the import aborts. After deleting the `"sections":[{"title":"","name":""}]` part the import runs without problems.

`{"uuid":"1CE4ADEB831141869D18F7D77B85EC36","updatedAt":1455218641,"securityLevel":"SL5","openContents":{"scope":"Never","tags":["WLAN"]},"contentsHash":"4c6d72c","title":"WLAN Hotspot","txTimestamp":1455218641,"createdAt":1415831265,"typ\
eName":"webforms.WebForm","secureContents":{"fields":[{"value":"uuuu","name":"username","type":"T","designation":"username"},{"value":"pppp","name":"password","type":"P","designation":"password"}],"passwordHistory":[{"value":"ppp2","time\
":1455218641}],"notesPlain":"some notes","sections":[{"title":"","name":""}]}}`

Thanks for your work.

**Comment by juanii** [comment]
Thank you very much for your feedback! It's already fixed and released.
This makes it very clear I have to work on error handling and write tests, though I don't think I'll write any tests for now :)

Regards
